[I 08:49:27.031 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 2022-09-18 08:49:27.640 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'allow_origin_pat' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-09-18 08:49:27.640 LabApp] 'jinja_template_vars' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-09-18 08:49:27.640 LabApp] 'shutdown_no_activity_timeout' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-18 08:49:27.640 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-09-18 08:49:27.650 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2022-09-18 08:49:27.650 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 08:49:27.656 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 08:49:27.657 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 08:49:27.658 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 08:49:27.658 NotebookApp] Jupyter Notebook 6.4.10 is running at:
[I 08:49:27.658 NotebookApp] http://jupyter-fatemehef98-2dnbinteract-2dtutorial-2dovdxdg41:8888/user/fatemehef98-nbinteract-tutorial-ovdxdg41/?token=...
[I 08:49:27.658 NotebookApp]  or http://127.0.0.1:8888/user/fatemehef98-nbinteract-tutorial-ovdxdg41/?token=...
[I 08:49:27.658 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 08:49:27.662 NotebookApp] No web browser found: could not locate runnable browser.
[I 08:49:27.940 NotebookApp] 302 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/ (10.2.2.15) 1.540000ms
[I 08:49:28.581 NotebookApp] 302 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/?token=-frdmMXWQ6eG93ParFk4Yw (131.188.6.13) 1.150000ms
[I 08:49:28.728 NotebookApp] 301 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab/?token=-frdmMXWQ6eG93ParFk4Yw (131.188.6.13) 2.560000ms
[I 08:49:37.096 NotebookApp] 301 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/static/favicons/favicon.ico (131.188.6.13) 0.790000ms
[I 2022-09-18 08:49:42.730 LabApp] Build is up to date
[I 08:52:20.543 NotebookApp] New terminal with automatic name: 1
[I 08:55:43.296 NotebookApp] Creating new notebook in 
[E 08:55:43.297 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491343940 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491343940', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 08:55:43.301 NotebookApp] Unhandled error
[E 08:55:43.302 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 08:55:43.302 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491343940 (131.188.6.13) 6.750000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 08:56:40.411 NotebookApp] Creating new notebook in 
[E 08:56:40.412 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491401053 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491401053', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 08:56:40.414 NotebookApp] Unhandled error
[E 08:56:40.415 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 08:56:40.415 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491401053 (131.188.6.13) 5.120000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 08:56:54.613 NotebookApp] Creating new notebook in 
[E 08:56:54.614 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491415257 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491415257', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 08:56:54.615 NotebookApp] Unhandled error
[E 08:56:54.616 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 08:56:54.616 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663491415257 (131.188.6.13) 4.390000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 08:57:25.452 NotebookApp] Uploading file to /widgets_html_ex.ipynb
[W 08:57:28.298 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663491448944 (131.188.6.13): Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 08:57:28.299 NotebookApp] Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 08:57:28.300 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663491448944 (131.188.6.13) 4.090000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 09:06:20.962 NotebookApp] Creating new file in 
[W 09:25:35.645 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663493136273 (131.188.6.13): Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 09:25:35.645 NotebookApp] Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 09:25:35.646 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663493136273 (131.188.6.13) 4.650000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab/tree/requirements.txt
[W 09:25:41.708 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663493142335 (131.188.6.13): Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 09:25:41.709 NotebookApp] Unreadable Notebook: /home/jovyan/widgets_html_ex.ipynb FileNotFoundError(2, 'No such file or directory')
[W 09:25:41.710 NotebookApp] 400 GET /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents/widgets_html_ex.ipynb?type=notebook&content=1&1663493142335 (131.188.6.13) 4.540000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab/tree/requirements.txt
[I 09:25:48.040 NotebookApp] Creating new notebook in 
[E 09:25:48.042 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493148664 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493148664', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 09:25:48.046 NotebookApp] Unhandled error
[E 09:25:48.047 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab/tree/requirements.txt",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 09:25:48.047 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493148664 (131.188.6.13) 9.520000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab/tree/requirements.txt
[I 09:25:56.513 NotebookApp] Creating new notebook in 
[E 09:25:56.513 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493156668 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493156668', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 09:25:56.515 NotebookApp] Unhandled error
[E 09:25:56.516 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 09:25:56.517 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493156668 (131.188.6.13) 5.170000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 09:26:03.045 NotebookApp] Creating new notebook in 
[E 09:26:03.045 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493163673 (131.188.6.13)
    HTTPServerRequest(protocol='https', host='hub-binder.mybinder.ovh', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493163673', version='HTTP/1.1', remote_ip='131.188.6.13')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 09:26:03.047 NotebookApp] Unhandled error
[E 09:26:03.048 NotebookApp] {
      "Host": "hub-binder.mybinder.ovh",
      "Accept": "*/*",
      "Referer": "https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 09:26:03.048 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-ovdxdg41/api/contents?1663493163673 (131.188.6.13) 4.610000ms referer=https://hub-binder.mybinder.ovh/user/fatemehef98-nbinteract-tutorial-ovdxdg41/lab
[I 09:33:03.740 NotebookApp] New terminal with automatic name: 2
[W 2022-10-13 12:23:35.449 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'allow_origin_pat' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-10-13 12:23:35.450 LabApp] 'jinja_template_vars' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-10-13 12:23:35.450 LabApp] 'shutdown_no_activity_timeout' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-13 12:23:35.450 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-10-13 12:23:35.460 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2022-10-13 12:23:35.460 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 12:23:35.472 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 12:23:35.474 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 12:23:35.475 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 12:23:35.476 NotebookApp] Jupyter Notebook 6.4.10 is running at:
[I 12:23:35.476 NotebookApp] http://jupyter-fatemehef98-2dnbinteract-2dtutorial-2dqctkowrk:8888/user/fatemehef98-nbinteract-tutorial-qctkowrk/?token=...
[I 12:23:35.476 NotebookApp]  or http://127.0.0.1:8888/user/fatemehef98-nbinteract-tutorial-qctkowrk/?token=...
[I 12:23:35.476 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:23:35.482 NotebookApp] No web browser found: could not locate runnable browser.
[I 12:23:37.267 NotebookApp] 302 GET /user/fatemehef98-nbinteract-tutorial-qctkowrk/ (10.0.5.15) 1.210000ms
[I 12:23:37.697 NotebookApp] 302 GET /user/fatemehef98-nbinteract-tutorial-qctkowrk/?token=C0IvBf8iQiu84StsnDq1kg (131.188.6.22) 1.010000ms
[I 12:23:37.833 NotebookApp] 301 GET /user/fatemehef98-nbinteract-tutorial-qctkowrk/lab/?token=C0IvBf8iQiu84StsnDq1kg (131.188.6.22) 1.910000ms
[I 12:23:42.353 NotebookApp] 301 GET /user/fatemehef98-nbinteract-tutorial-qctkowrk/static/favicons/favicon.ico (131.188.6.22) 0.490000ms
[I 2022-10-13 12:23:45.712 LabApp] Build is up to date
[I 12:24:05.082 NotebookApp] New terminal with automatic name: 1
[I 12:24:06.374 NotebookApp] New terminal with automatic name: 2
[I 12:24:25.734 NotebookApp] New terminal with automatic name: 3
[I 13:23:13.035 NotebookApp] Creating new notebook in 
[E 13:23:13.036 NotebookApp] Uncaught exception POST /user/fatemehef98-nbinteract-tutorial-qctkowrk/api/contents?1665667391305 (131.188.6.22)
    HTTPServerRequest(protocol='https', host='hub.gke2.mybinder.org', method='POST', uri='/user/fatemehef98-nbinteract-tutorial-qctkowrk/api/contents?1665667391305', version='HTTP/1.1', remote_ip='131.188.6.22')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 207, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 159, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 172, in new_notebook
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 40, in validate
        output.data = data
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 300, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 348, in iter_validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 61, in get_validator
        if version_minor is None:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 100, in _get_schema_json
        schema_json = json.load(f)
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
[W 13:23:13.043 NotebookApp] Unhandled error
[E 13:23:13.044 NotebookApp] {
      "Host": "hub.gke2.mybinder.org",
      "Accept": "*/*",
      "Referer": "https://hub.gke2.mybinder.org/user/fatemehef98-nbinteract-tutorial-qctkowrk/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 13:23:13.044 NotebookApp] 500 POST /user/fatemehef98-nbinteract-tutorial-qctkowrk/api/contents?1665667391305 (131.188.6.22) 10.210000ms referer=https://hub.gke2.mybinder.org/user/fatemehef98-nbinteract-tutorial-qctkowrk/lab
[I 13:38:31.526 NotebookApp] Uploading file to /tutorial.html
